# SD701

## Sparse matrices

The objective of this notebook is to learn to work with sparse matrices.

## Import

In [1]:
import numpy as np

In [2]:
import scipy.sparse as sparse

## Data structure

We first focus on the [csr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. 

In [3]:
# random matrix (dense format)
X_dense = np.random.randint(2, size = (10,5))

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [6]:
X_csr.shape

(10, 5)

In [7]:
X_csr.nnz

21

The data structure consists of 3 vectors:

In [8]:
X_csr.indices

array([2, 4, 2, 3, 4, 1, 1, 3, 0, 3, 2, 4, 0, 1, 2, 3, 0, 2, 4, 2, 4],
      dtype=int32)

In [9]:
X_csr.indptr

array([ 0,  2,  5,  6,  8, 10, 12, 16, 16, 19, 21], dtype=int32)

In [10]:
X_csr.data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Changing these vectors changes the matrix:

In [11]:
X_csr.data = np.random.choice((1,2,3,4,5), size = len(X_csr.data))

In [12]:
np.array(X_csr.todense())

array([[0, 0, 3, 0, 5],
       [0, 0, 1, 2, 2],
       [0, 5, 0, 0, 0],
       [0, 1, 0, 4, 0],
       [5, 0, 0, 2, 0],
       [0, 0, 5, 0, 5],
       [1, 5, 3, 5, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 2, 0, 1],
       [0, 0, 2, 0, 5]])

In [13]:
X_dense = np.array(X_csr.todense())

The [csc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format is the analogue of the csr format for columns.

In [14]:
X_csc = sparse.csc_matrix(X_dense)

In [15]:
X_csc

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Column format>

In [16]:
# transposing a matrix in csr format is a matrix in csc format
X_csr.T

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Column format>

## Construction

In practice, sparse data are stored as a list of pairs (row id, col id) triplets (row id, col id, value) in text or csv files.<br> 
This is the [coo](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html) (COOrdinate) format. 

In [17]:
X_coo = sparse.coo_matrix(X_dense)

In [18]:
X_coo.row

array([0, 0, 1, 1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 8, 8, 8, 9, 9],
      dtype=int32)

In [19]:
X_coo.col

array([2, 4, 2, 3, 4, 1, 1, 3, 0, 3, 2, 4, 0, 1, 2, 3, 0, 2, 4, 2, 4],
      dtype=int32)

In [20]:
X_coo.data

array([3, 5, 1, 2, 2, 5, 1, 4, 5, 2, 5, 5, 1, 5, 3, 5, 2, 2, 1, 2, 5])

Sparse matrices can be easily moved from one format to another. This can be used to get the list of entries of a matrix in CSR format:

In [21]:
X_coo = sparse.coo_matrix(X_csr)

In [22]:
X_coo.row

array([0, 0, 1, 1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 8, 8, 8, 9, 9],
      dtype=int32)

In [23]:
X_coo.col

array([2, 4, 2, 3, 4, 1, 1, 3, 0, 3, 2, 4, 0, 1, 2, 3, 0, 2, 4, 2, 4],
      dtype=int32)

In [24]:
X_csr = sparse.csr_matrix(X_coo)

In [25]:
X_csr

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

Construction of a matrix from a list of links:

In [26]:
n, m = 100, 200

In [27]:
pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(100)]

In [28]:
row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [29]:
X = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [30]:
X

<100x200 sparse matrix of type '<class 'numpy.int64'>'
	with 100 stored elements in Compressed Sparse Row format>

Zero matrix:

In [31]:
X = sparse.csr_matrix((n,m))

In [32]:
X

<100x200 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

Diagonal matrix:

In [33]:
X = sparse.diags(np.arange(5))

In [34]:
X

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [35]:
X = sparse.csr_matrix(X)

In [36]:
X

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [37]:
X = sparse.csr_matrix(np.random.randint(2, size = (10,5)))

In [78]:
X.todense()
X.nnz

28

* Set one of the entries to 0 by modifying the data vector. 
* What do you observe on the number of non-zero entries stored?
* Use the following method to get the matrix in proper format.

In [80]:
X.data[12] = 0
X.data

array([2, 3, 1, 2, 2, 3, 4, 4, 4, 2, 1, 3, 0, 4, 2, 4, 4, 1, 4, 1, 3, 4,
       1, 2, 1, 3, 3, 3])

In [81]:
X.nnz

28

In [82]:
X.eliminate_zeros()

In [83]:
X.nnz

27

## Operations

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [40]:
n, m = 10, 15

pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(20)]

row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [41]:
X = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [42]:
X.dot(np.ones(m))

array([2., 2., 4., 2., 1., 1., 3., 2., 0., 3.])

In [43]:
X.T.dot(np.ones(n))

array([1., 0., 1., 0., 2., 0., 4., 1., 1., 1., 1., 1., 0., 6., 1.])

In [44]:
X.T.dot(X)

<15x15 sparse matrix of type '<class 'numpy.int64'>'
	with 37 stored elements in Compressed Sparse Column format>

In [45]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.int64'>'
	with 45 stored elements in Compressed Sparse Row format>

In [72]:
X.data = np.random.choice((1,2,3,4), size = len(X.data))

In [73]:
X

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [74]:
Y = X > 1

In [76]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 22 stored elements in Compressed Sparse Row format>

In [50]:
pairs = [(np.random.choice(n), np.random.choice(m)) for i in range(20)]

row = [pair[0] for pair in pairs]
col = [pair[1] for pair in pairs]
data = np.ones_like(row)

In [51]:
Y = sparse.csr_matrix((data, (row, col)), shape = (n, m))

In [52]:
2 * X + 5 * Y

<10x15 sparse matrix of type '<class 'numpy.int64'>'
	with 37 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [53]:
X = sparse.csr_matrix(np.random.randint(2, size = (20,3)))

* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 
* Do the same for columns.

In [54]:
n, m = X.shape 

In [55]:
normalizing_diag = sparse.csr_matrix(sparse.diags(X.dot(np.ones(m))))

In [56]:
normalizing_diag.data = 1 / normalizing_diag.data

## Slicing

Sparse matrices can be sliced like numpy arrays. The CSR format is more efficient for row slicing (although column slicing is possible), while the CSC format is more efficient for column slicing.

In [57]:
X = sparse.csr_matrix(np.random.randint(2, size = (10,5)))

In [58]:
X[1]

<1x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [59]:
X[1].todense()

matrix([[0, 1, 1, 1, 1]])

In [60]:
X[:3]

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [61]:
X[:3].todense()

matrix([[0, 1, 1, 1, 1],
        [0, 1, 1, 1, 1],
        [1, 1, 0, 1, 0]])